
const list = [
{word: "accolade", def: "a tangible symbol signifying approval or distinction"},
{word: "acrimony", def: "a rough and bitter manner"},
{word: "angst", def: "an acute but unspecific feeling of anxiety"},
{word: "anomaly", def: "deviation from the normal or common order or form or rule"},
{word: "antidote", def: "a remedy that stops or controls the effects of a poison"},
{word: "lignify", def: "make rigid and woody by the deposition of lignin in cell walls"},
{word: "bona fide", def: "not counterfeit or copied"},
{word: "boondoggle", def: "work of little or no value done merely to look busy"},
{word: "bourgeois", def: "being of the property-owning class"},
{word: "bravado", def: "a swaggering show of courage"},
{word: "brogue", def: "a thick and heavy shoe"},
{word: "brusque", def: "rudely abrupt or blunt in speech or manner"},
{word: "Byzantine", def: "of or relating to or characteristic of the Byzantine Empire or the ancient city of Byzantium"},
{word: "cacophony", def: "loud confusing disagreeable sounds"},
{word: "camaraderie", def: "the quality of affording easy familiarity and sociability"},
{word: "capricious", def: "determined by chance or impulse rather than by necessity"},
{word: "carte blanche", def: "complete freedom or authority to act"},
{word: "caustic", def: "capable of destroying or eating away by chemical action"},
{word: "charisma", def: "personal attractiveness that enables you to influence others"},
{word: "cloying", def: "overly sweet"},
{word: "deja vu", def: "the experience of thinking a new situation already occurred"},
{word: "dichotomy", def: "a classification into two opposed parts or subclasses"},
{word: "dilettante", def: "an amateur engaging in an activity without serious intention"},
{word: "disheveled", def: "in disarray; extremely disorderly"},
{word: "elan", def: "enthusiastic and assured vigor and liveliness"},
{word: "ennui", def: "the feeling of being bored by something tedious"},
{word: "epitome", def: "a standard or typical example"},
{word: "equanimity", def: "steadiness of mind under stress"},
{word: "equivocate", def: "be deliberately ambiguous or unclear"},
{word: "esoteric", def: "understandable only by an enlightened inner circle"},
{word: "euphemism", def: "an inoffensive expression substituted for an offensive one"},
{word: "fait accompli", def: "an irreversible accomplishment"},
{word: "fastidious", def: "giving careful attention to detail"},
{word: "faux pas", def: "a socially awkward or tactless act"},
{word: "fiasco", def: "a complete failure or collapse"},
{word: "finagle", def: "achieve something by means of trickery or devious methods"},
{word: "Freudian slip", def: "a slip-up that (according to Sigmund Freud) result…conscious processes in normal healthy individuals"},
{word: "glib", def: "artfully persuasive in speech"},
{word: "gregarious", def: "temperamentally seeking and enjoying the company of others"},
{word: "harbinger", def: "something indicating the approach of something or someone"},
{word: "hedonist", def: "someone motivated by desires for sensual pleasures"},
{word: "heresy", def: "a belief that rejects the orthodox tenets of a religion"},
{word: "idiosyncratic", def: "peculiar to the individual"},
{word: "idyllic", def: "charmingly simple and serene"},
{word: "indelicate", def: "slightly indecent, offensive, or improper"},
{word: "infinitesimal", def: "immeasurably small"},
{word: "insidious", def: "working or spreading in a hidden and usually injurious way"},
{word: "junket", def: "dessert made of sweetened milk coagulated with rennet"},
{word: "kitsch", def: "excessively garish or sentimental art"},
{word: "litany", def: "any long and tedious address or recital"},
{word: "lurid", def: "glaringly vivid and graphic; marked by sensationalism"},
{word: "Machiavellian", def: "of or relating to amoral or conniving political principles"},
{word: "malaise", def: "a general feeling of discomfort, uneasiness, or depression"},
{word: "malinger", def: "avoid responsibilities and duties"},
{word: "mantra", def: "a sacred utterance or poetic hymn in Vedism"},
{word: "maudlin", def: "effusively or insincerely emotional"},
{word: "mercenary", def: "a person hired to fight for another country than their own"},
{word: "minimalist", def: "a conservative advocating only minor reforms in government"},
{word: "misnomer", def: "an incorrect or unsuitable name"},
{word: "narcissist", def: "someone who is excessively self-centered"},
{word: "nirvana", def: "the beatitude that transcends the cycle of reincarnation"},
{word: "non sequitur", def: "a reply that has no relevance to what preceded it"},
{word: "triskaidekaphobia", def: "the fear or irrational hatred for the number thirteen"},
{word: "oblivion", def: "the state of being disregarded or forgotten"},
{word: "ogle", def: "stare or look at, especially with amorous intentions"},
{word: "ostentatious", def: "intended to attract notice and impress others"},
{word: "ostracize", def: "expel from a community or group"},
{word: "panacea", def: "hypothetical remedy for all ills or diseases"},
{word: "paradox", def: "a statement that contradicts itself"},
{word: "peevish", def: "easily irritated or annoyed"},
{word: "perfunctory", def: "hasty and without attention to detail; not thorough"},
{word: "philistine", def: "a person who is uninterested in intellectual pursuits"},
{word: "precocious", def: "characterized by exceptionally early development"},
{word: "propriety", def: "correct behavior"},
{word: "quid pro quo", def: "something given in exchange for something else"},
{word: "quintessential", def: "representing the perfect example of a class or quality"},
{word: "red herring", def: "diversion intended to distract attention from the main issue"},
{word: "revel", def: "take delight in"},
{word: "rhetoric", def: "study of the technique for using language effectively"},
{word: "scintillating", def: "having brief brilliant points or flashes of light"},
{word: "spartan", def: "unsparing and uncompromising in discipline or judgment"},
{word: "stigma", def: "a symbol of disgrace or infamy"},
{word: "stoic", def: "seeming unaffected by pleasure or pain; impassive"},
{word: "suave", def: "having a sophisticated charm"},
{word: "Svengali", def: "someone (usually maleficent) who tries to persuade or force another person to do his bidding"},
{word: "sycophant", def: "a person who tries to please someone to gain an advantage"},
{word: "teetotaler", def: "someone who abstains from drinking alcoholic beverages"},
{word: "espionage", def: "the practice of spying or of using spies, typically by governments to obtain political and military information"},
{word: "tirade", def: "a speech of violent denunciation"},
{word: "tryst", def: "a secret rendezvous, especially a romantic one"},
{word: "ubiquitous", def: "being present everywhere at once"},
{word: "unrequited", def: "not returned in kind"},
{word: "untenable", def: "incapable of being defended or justified"},
{word: "vicarious", def: "experienced at secondhand"},
{word: "vile", def: "morally reprehensible"},
{word: "waft", def: "a long flag; often tapering"},
{word: "white elephant", def: "a valuable possession whose upkeep is excessively expensive"},
{word: "zealous", def: "marked by active interest and enthusiasm"},
{word: "dimethyltryptamine", def: "a serotonergic hallucinogen found in several plants, especially Prestonia amazonica (Apocynaceae) and in mammalian brain, blood, and urine."}
];

export default list